# Generated by Django 3.2.11 on 2022-01-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20220125_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishDate',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
